### ISSUE TITLE
panic: invalid argument to Int63n

### ISSUE THREAD

**Issue by Evildethow** [dogmatiq/linger#66] opened 2022-11-29 03:16 UTC
We've noticed when configuring Dogma services using `WithNetworking(...)`, for example:

```go
// Set up the Dogma engine.
	provide(func(
		app dogma.Application,
		p persistence.Provider,
		l logging.Logger,
	) *verity.Engine {
		targetPort := util.GetEnv("DOGMAAPI_PORT", "50555")
		namespace := util.GetEnv("NAMESPACE", "default")
		return verity.New(
			app,
			verity.WithPersistence(p),
			verity.WithLogger(l),
			verity.WithNetworking(
				verity.WithListenAddress(fmt.Sprintf(":%s", targetPort)),
				verity.WithDiscoverer(discoverkit.StaticTargetDiscoverer{
					discoverkit.Target{
						Name:        fmt.Sprintf("stack-casinogroup.%s.svc.cluster.local:50555", namespace),
						DialOptions: []grpc.DialOption{grpc.WithTransportCredentials(insecure.NewCredentials())},
					},
				}),
			),
		)
	})

```

that we periodically hit the following stacktrace:

```go
panic: invalid argument to Int63n

goroutine 90 [running]:
math/rand.(*Rand).Int63n(0x1400021fd88?, 0x3ff0000000000000?)
        /usr/local/go/src/math/rand/rand.go:110 +0xec
math/rand.Int63n(...)
        /usr/local/go/src/math/rand/rand.go:327
github.com/dogmatiq/linger.Rand(0x2?, 0x4197d78400000000?)
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/linger@v0.2.1/jitter.go:42 +0x40
github.com/dogmatiq/linger.FullJitter(0x10094d94c?)
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/linger@v0.2.1/jitter.go:14 +0x24
github.com/dogmatiq/linger/backoff.WithTransforms.func1({0x100bf8f80?, 0x1400007e540?}, 0x0?)
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/linger@v0.2.1/backoff/strategy.go:95 +0x58
github.com/dogmatiq/linger/backoff.(*Counter).Fail(0x0?, {0x100bf8f80?, 0x1400007e540?})
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/linger@v0.2.1/backoff/counter.go:40 +0x90
github.com/dogmatiq/linger/backoff.(*Counter).Sleep(0x140001ae840?, {0x100c026b8, 0x140003c2b00}, {0x100bf8f80?, 0x1400007e540?})
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/linger@v0.2.1/backoff/counter.go:53 +0x34
github.com/dogmatiq/discoverkit.(*ApplicationDiscoverer).DiscoverApplications(0x1400035c900, {0x100c026b8, 0x140003c2b00}, {{0x140001ae840, 0x2f}, {0x140001c49a0, 0x2, 0x2}}, 0x0?)
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/discoverkit@v0.1.2/application.go:116 +0x114
github.com/dogmatiq/verity.(*Engine).targetDiscovered(0x14000376b40, {0x100c026b8, 0x140003c2b00}, {{0x140001ae840, 0x2f}, {0x140001c49a0, 0x2, 0x2}}, 0x0?)
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/verity@v0.1.1/network.go:156 +0x1a0
created by github.com/dogmatiq/verity.(*Engine).runDiscoverer.func2
        /Users/sameaste/go/pkg/mod/github.com/dogmatiq/verity@v0.1.1/network.go:131 +0x128
Error: exit status 2
```

I've been able to reproduce the issue in isolation using the following code:

```go
package main

import (
	"github.com/dogmatiq/linger"
	"math"
)

func main() {
	_ = linger.FullJitter(math.MaxInt64)
}
```

**Comment by jmalloc** [comment] 2022-11-29 04:10
Duplicate of #18, fixes in v0.2.2

**Closed as completed by jmalloc** 2022-11-29 04:10 UTC
